config/routes.rb
Rails.application.routes.draw do

  resources :submit, :only => [:new, :create]
  resources :populations

  root "home#index"
  
  get "populations/new", to: "populations#new"

end

app/models/population.rb
class Population < ActiveRecord::Base
    def self.search(term)
        if term
            where('name LIKE ?', "%#{term}%").order('id DESC')
        else
            order('id DESC') 
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/populations_controller.rb
class PopulationsController < ApplicationController
  before_action :set_population, only: [:show, :edit, :update, :destroy]

  # GET /populations
  # GET /populations.json
  def index
    @populations = Population.all
    @population = Population.paginate(:page => params[:page], :per_page => 5)
    
    @population = Population.search(params[:term])
  end

  # GET /populations/1
  # GET /populations/1.json
  def show

  end

  # GET /populations/new
  def new
    @population = Population.new
  end

  # GET /populations/1/edit
  def edit
    
  end

  
  

  # POST /populations
  # POST /populations.json
  def create
    @population = Population.new(population_params)

    respond_to do |format|
      if @population.save
        format.html { redirect_to @population, notice: 'Population was successfully created.' }
        format.json { render :show, status: :created, location: @population }
      else
        format.html { render :new }
        format.json { render json: @population.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /populations/1
  # PATCH/PUT /populations/1.json
  def update
    respond_to do |format|
      if @population.update(population_params)
        format.html { redirect_to @population, notice: 'Population was successfully updated.' }
        format.json { render :show, status: :ok, location: @population }
      else
        format.html { render :edit }
        format.json { render json: @population.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /populations/1
  # DELETE /populations/1.json
  def destroy
    @population.destroy
    respond_to do |format|
      format.html { redirect_to populations_url, notice: 'Population was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_population
      @population = Population.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def population_params
      params.require(:population).permit(:name, :email, :id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/populations_helper.rb
module PopulationsHelper
end

app/views/home/index.html.erb
<h1><center>Dashboard Home</center></h1>

<%= render "layouts/navigation" %>
<%= yield %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "View Population", populations_path %></li>
          <li><%= link_to "Create Population", new_population_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li>Test</li>
                <li>Test</li>
              </ul>
            </li>
        </ul>
   
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SaasDatabaseCpanel</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/populations/_form.html.erb
<%= form_for(@population) do |f| %>
  <% if @population.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@population.errors.count, "error") %> prohibited this population from being saved:</h2>

      <ul>
      <% @population.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="population-submit-box">
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :id %><br>
      <%= f.number_field :id %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/populations/edit.html.erb
<h1>Editing Population</h1>

<%= render 'form' %>

<%= link_to 'Show', @population %> |
<%= link_to 'Back', populations_path %>

app/views/populations/index.html.erb
<p id="notice"><%= notice %></p>

<h1><center>Listing Populations</center></h1>
<%= render "layouts/navigation" %>

<div class="center">
  <%= form_tag(populations_path, method: :get) do %>
    <%= text_field_tag :term, params[:term] %>
    <%= submit_tag 'Search', name: nil %>
  <% end %>
</div>

<div class="container demo">
  <table class="datatable table table-striped table-bordered">
    <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Unique Number</th>
      </tr>
    </thead>
    <tbody>
      <tr class="gradeX">
        <% @population.each do |population| %>
          <tr>
            <td><%= population.name %></td>
            <td><%= population.email %></td>
            <td><%= population.id %></td>
            <td><%= link_to 'Show', population %></td>
            <td><%= link_to 'Edit', edit_population_path(population) %></td>
            <td><%= link_to 'Destroy', population, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tr>
    </tbody>
  </table>
  <%# will_paginate @population %>
</div>

app/views/populations/new.html.erb
<h1><center>New Population</center></h1>
<%= render "layouts/navigation" %>
<%= render 'form' %>

app/views/populations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @population.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @population.email %>
</p>

<p>
  <strong>Id:</strong>
  <%= @population.id %>
</p>

<%= link_to 'Edit', edit_population_path(@population) %> |
<%= link_to 'Back', populations_path %>